# Generated by Django 5.1.7 on 2025-06-07 08:52

import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_service', models.CharField(max_length=20, null=True)),
                ('operating_hours', models.CharField(max_length=20, null=True)),
                ('owner_name', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 20 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=20, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('clinic_name', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 20 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=20, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('clinic_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('address', models.TextField()),
                ('website_url', models.URLField(blank=True, null=True)),
                ('digital_clinic_email', models.EmailField(blank=True, max_length=20, null=True)),
                ('terms_and_conditions_accepted', models.BooleanField(default=False)),
                ('clinic_profile_picture', models.ImageField(blank=True, max_length=50, null=True, upload_to='clinic_profile_picture/')),
                ('digital_clinic_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_profile', to=settings.AUTH_USER_MODEL)),
                ('specialization', models.ManyToManyField(blank=True, to='specialization.doctorspecializations')),
            ],
            options={
                'db_table': 'digital_clinic',
            },
        ),
        migrations.CreateModel(
            name='DigitalClinicMedicalRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_document', models.FileField(blank=True, null=True, upload_to='medical_document/')),
                ('digital_clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='clinics.digitalclinic')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalClinicPaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital_clinic_bank_account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=10)),
                ('uoi_id', models.CharField(max_length=10)),
                ('digital_clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_information', to='clinics.digitalclinic')),
            ],
        ),
    ]
