# Generated by Django 5.1.7 on 2025-03-14 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('clinic_type', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('website_url', models.URLField(blank=True, null=True)),
                ('digital_clinic_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'digital_clinic',
            },
        ),
        migrations.CreateModel(
            name='DigitalClinicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_offered', models.CharField(max_length=255)),
                ('available_service', models.TextField()),
                ('operating_hours', models.CharField(max_length=255)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinics.digitalclinic')),
            ],
        ),
    ]
