# Generated by Django 5.1.7 on 2025-04-21 22:38

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalClinicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_offered', models.CharField(max_length=20)),
                ('available_service', models.TextField()),
                ('operating_hours', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 20 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=20, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('clinic_type', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('website_url', models.URLField(blank=True, null=True)),
                ('digital_clinic_email', models.EmailField(blank=True, max_length=20, null=True)),
                ('terms_and_conditions_accepted', models.BooleanField(default=False)),
                ('clinic_profile_picture', models.ImageField(blank=True, max_length=30, null=True, upload_to='clinic_profile_picture/')),
                ('digital_clinic_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_profile', to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(blank=True, related_name='clinics', to='clinics.digitalclinicservice')),
            ],
            options={
                'db_table': 'digital_clinic',
            },
        ),
    ]
