# Generated by Django 5.1.7 on 2025-06-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalclinic',
            name='digital_clinic_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
