# Generated by Django 5.1.7 on 2025-03-27 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('user', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalclinic',
            name='digital_clinic_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_profile', to='user.user'),
        ),
    ]
