# Generated by Django 5.1.7 on 2025-06-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_alter_digitalclinic_digital_clinic_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalclinic',
            name='website_url',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='digitalclinicpaymentinformation',
            name='ifsc_code',
            field=models.CharField(max_length=11),
        ),
    ]
