# Generated by Django 5.1.7 on 2025-05-31 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_alter_digitalclinic_clinic_profile_picture'),
        ('specialization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalclinic',
            name='clinic_profile_picture',
        ),
        migrations.AddField(
            model_name='digitalclinic',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specialization.doctorspecializations'),
        ),
        migrations.CreateModel(
            name='DigitalClinicMedicalRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_document', models.FileField(blank=True, null=True, upload_to='medical_document/')),
                ('digital_clinic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='clinics.digitalclinic')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalClinicPaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Digital_clinic_bank_account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=10)),
                ('uoi_id', models.CharField(max_length=10)),
                ('Digital_clinic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_information', to='clinics.digitalclinic')),
            ],
        ),
    ]
