# Generated by Django 5.1.7 on 2025-03-29 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_alter_digitalclinic_digital_clinic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalclinic',
            name='digital_clinic_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DigitalClinicMedicalRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital_lab_certificates', models.FileField(blank=True, null=True, upload_to='digital_lab_certificates/')),
                ('digital_clinic_pharmacy_licence', models.FileField(blank=True, null=True, upload_to='digital_clinic_pharmacy_licence/')),
                ('digital_clinic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='clinics.digitalclinic')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalClinicPaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Digital_clinic_bank_account_number', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=255)),
                ('uoi_id', models.CharField(max_length=255)),
                ('Digital_clinic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_information', to='clinics.digitalclinic')),
            ],
        ),
    ]
