# Generated by Django 5.1.7 on 2025-03-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_digitalclinic_digital_clinic_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalclinic',
            name='clinic_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='digitalclinic',
            name='digital_clinic_email',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='digitalclinic',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='digitalclinicpaymentinformation',
            name='Digital_clinic_bank_account_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='digitalclinicpaymentinformation',
            name='ifsc_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='digitalclinicpaymentinformation',
            name='uoi_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='digitalclinicservice',
            name='operating_hours',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='digitalclinicservice',
            name='specialization_offered',
            field=models.CharField(max_length=20),
        ),
    ]
