# Generated by Django 5.1.7 on 2025-06-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_alter_digitalclinic_website_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalclinicpaymentinformation',
            name='digital_clinic_bank_account_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
