# Generated by Django 5.1.7 on 2025-05-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_remove_digitalclinic_clinic_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitalclinicpaymentinformation',
            old_name='Digital_clinic_bank_account_number',
            new_name='digital_clinic_bank_account_number',
        ),
        migrations.RenameField(
            model_name='digitalclinicpaymentinformation',
            old_name='Digital_clinic_name',
            new_name='digital_clinic_name',
        ),
        migrations.AddField(
            model_name='digitalclinic',
            name='clinic_profile_picture',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='clinic_profile_picture/'),
        ),
    ]
