# Generated by Django 5.1.7 on 2025-05-31 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_rename_digital_clinic_bank_account_number_digitalclinicpaymentinformation_digital_clinic_bank_accoun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitalclinic',
            old_name='name',
            new_name='clinic_name',
        ),
    ]
