# Generated by Django 5.1.7 on 2025-07-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_digitalclinicpaymentinformation_digital_clinic_bank_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalclinicpaymentinformation',
            name='uoi_id',
            field=models.CharField(max_length=30),
        ),
    ]
