# Generated by Django 5.1.7 on 2025-06-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_rename_digital_clinic_name_digitalclinicmedicalrecords_digital_clinic_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalclinic',
            name='services',
        ),
        migrations.AddField(
            model_name='digitalclinic',
            name='available_service',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='digitalclinic',
            name='operating_hours',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='DigitalClinicService',
        ),
    ]
