# Generated by Django 5.1.7 on 2025-07-11 08:31

import remedizz_apps.doctors.models.doctor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_alter_digitalclinic_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalclinic',
            name='owner_name',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 20 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=50, null=True, unique=True, validators=[remedizz_apps.doctors.models.doctor.NameWithSpaceValidator], verbose_name='username'),
        ),
    ]
