# Generated by Django 5.1.7 on 2025-07-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_alter_digitalclinic_clinic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalclinicpaymentinformation',
            name='uoi_id',
            field=models.CharField(max_length=50),
        ),
    ]
