# Generated by Django 5.1.7 on 2025-07-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_alter_digitalclinicpaymentinformation_uoi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalclinicpaymentinformation',
            name='digital_clinic_bank_account_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
