# Generated by Django 5.1.7 on 2025-03-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='prescription',
            field=models.FileField(blank=True, max_length=30, null=True, upload_to='patients/prescriptions/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='record',
            field=models.FileField(blank=True, max_length=30, null=True, upload_to='patients/records/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reports',
            field=models.FileField(blank=True, max_length=30, null=True, upload_to='patients/reports/'),
        ),
    ]
