# Generated by Django 5.1.7 on 2025-04-11 09:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField(blank=True, null=True)),
                ('record', models.FileField(blank=True, max_length=30, null=True, upload_to='patients/child/records/')),
                ('prescription', models.FileField(blank=True, max_length=30, null=True, upload_to='patients/child/prescriptions/')),
                ('reports', models.FileField(blank=True, max_length=30, null=True, upload_to='patients/child/reports/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='patients.patient')),
            ],
            options={
                'db_table': 'child_patient',
            },
        ),
    ]
