# Generated by Django 5.1.7 on 2025-05-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_childpatient_relation_alter_childpatient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_profile_picture',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='patient_profile_pictures/'),
        ),
    ]
