# Generated by Django 5.1.7 on 2025-05-31 06:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_patient_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childpatient',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='childpatient',
            name='record',
        ),
        migrations.RemoveField(
            model_name='childpatient',
            name='reports',
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('Report', 'Report'), ('Prescription', 'Prescription'), ('Invoice', 'Invoice')], max_length=30)),
                ('record_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('upload_record', models.ImageField(blank=True, max_length=50, null=True, upload_to='patient_record/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'db_table': 'patient_records',
            },
        ),
    ]
