# Generated by Django 5.1.7 on 2025-06-04 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_childpatient_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='record_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
