# Generated by Django 5.1.7 on 2025-06-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_records_record_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='added_by',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Patient')], default='Patient', max_length=30),
        ),
    ]
