# Generated by Django 5.1.2 on 2025-03-11 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("remedizz_auth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
    ]
