# Generated by Django 5.1.7 on 2025-04-10 08:28

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=50)),
                ('college_passing_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_profile', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 20 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=20, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('specialization', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist')], max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('doctor_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('doctor_email', models.EmailField(blank=True, max_length=30, null=True)),
                ('doctor_profile_picture', models.ImageField(blank=True, max_length=30, null=True, upload_to='doctor_profile_pictures/')),
                ('preferred_language', models.CharField(max_length=15)),
                ('terms_and_conditions_accepted', models.BooleanField(default=False)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_year', models.DateField(null=True)),
                ('registration_council', models.CharField(blank=True, max_length=50, null=True)),
                ('doctor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_education', to='doctors.education')),
                ('work_experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_experience', to='doctors.workexperience')),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('Video Call', 'Video Call'), ('Audio Call', 'Audio Call'), ('Chat', 'Chat')], max_length=20, null=True)),
                ('appointment_date', models.DateField(null=True)),
                ('slot', models.TimeField(null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor')),
            ],
        ),
    ]
