# Generated by Django 5.1.7 on 2025-03-14 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist')], max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=255)),
                ('college_name', models.CharField(max_length=255)),
                ('college_passing_year', models.PositiveIntegerField()),
                ('preferred_language', models.CharField(max_length=100)),
                ('terms_and_conditions_accepted', models.BooleanField(default=False)),
                ('doctor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('video_call_afternoon_slot', models.TimeField(blank=True, null=True)),
                ('video_call_evening_slot', models.TimeField(blank=True, null=True)),
                ('audio_call_afternoon_slot', models.TimeField(blank=True, null=True)),
                ('audio_call_evening_slot', models.TimeField(blank=True, null=True)),
                ('chat_afternoon_slot', models.TimeField(blank=True, null=True)),
                ('chat_evening_slot', models.TimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor')),
            ],
        ),
    ]
