# Generated by Django 5.1.7 on 2025-07-10 11:11

import remedizz_apps.doctors.models.doctor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 20 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=20, null=True, unique=True, validators=[remedizz_apps.doctors.models.doctor.NameWithSpaceValidator], verbose_name='username'),
        ),
    ]
