# Generated by Django 5.1.7 on 2025-03-29 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_doctor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=50)),
                ('college_passing_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_profile', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='college_passing_year',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='audio_call_afternoon_slot',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='audio_call_evening_slot',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='chat_afternoon_slot',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='chat_evening_slot',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='video_call_afternoon_slot',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='video_call_evening_slot',
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_profile_pictures/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='registration_council',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='registration_year',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='appointment_type',
            field=models.CharField(choices=[('Video Call', 'Video Call'), ('Audio Call', 'Audio Call'), ('Chat', 'Chat')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='slot',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='preferred_language',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist')], max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='appointment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_education', to='doctors.education'),
        ),
    ]
