# Generated by Django 5.1.7 on 2025-04-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctorschedule_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailabilityexception',
            options={'ordering': ['doctor', 'date', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailabilityexception',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctoravailabilityexception',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailabilityexception',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='buffer_time',
            field=models.PositiveIntegerField(default=0, help_text='Gap after each slot in minutes'),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='slot_duration',
            field=models.PositiveIntegerField(default=15, help_text='Duration of each slot in minutes'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='appointment_type',
            field=models.CharField(blank=True, choices=[('Video Call', 'Video Call'), ('Audio Call', 'Audio Call'), ('Chat', 'Chat')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailabilityexception',
            unique_together={('doctor', 'date', 'start_time', 'end_time')},
        ),
    ]
