# Generated by Django 5.1.7 on 2025-03-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_education_workexperience_remove_doctor_college_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_profile_picture',
            field=models.ImageField(blank=True, max_length=30, null=True, upload_to='doctor_profile_pictures/'),
        ),
    ]
