# Generated by Django 5.1.7 on 2025-05-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctoravailabilityexception_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_profile_picture',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='doctor_profile_pictures/'),
        ),
    ]
