# Generated by Django 5.1.7 on 2025-05-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_doctor_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='education',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='doctors.education'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='work_experience',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='doctors.workexperience'),
        ),
    ]
