# Generated by Django 5.1.7 on 2025-06-02 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctor_clinic_address_doctor_clinic_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorMedicalRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_document', models.FileField(blank=True, null=True, upload_to='medical_document/')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='doctors.doctor')),
            ],
        ),
    ]
